name             'chef-splunk-windows'
maintainer       'Biola University'
maintainer_email 'jared.king@biola.edu'
license          'Apache 2.0'
description      'Installs and configures the Splunk Universal Forwarder on Windows servers'
long_description 'Installs and configures the Splunk Universal Forwarder on Windows servers'
source_url       'https://github.com/biola/chef-splunk-windows'
issues_url       'https://github.com/biola/chef-splunk-windows/issues'
version          '0.4.6'

depends          'chef-vault', '>= 1.0'
depends          'windows', '~> 1.34'
